### ISSUE TITLE
Question with setState syntax 

### ISSUE THREAD

**Issue by maggiew61** [Annilla/react-shopping-cart#2]
在 App.js 檔案裡面,  我對大大寫的return { productList: newProductList }; 有2個地方想請教

```
    this.setState(state => {
      let newProductList = state.productList.map(el =>{
        if (el.id === p.id) { // 只改變有相同 ID 產品的數量
          return { ...el, qty: Number(buyQTY) };
        } else {
          return el;
        }
      });
      return { productList: newProductList };
    });
```
1) 最後一行
```
 return { productList: newProductList };
```
 這個只會改寫state裡面的productList嗎? 假設state裡面還有其他值, 是不會被影響的吧. 我這樣問是因為我以前是這樣寫, 這樣我就知道我只會覆蓋productList這個值
```
   this.setState({
     productList:newProductList
   })
```

2) 其實第二題跟react不相關的, 是對於es6 syntax還不夠熟悉...
```
   this.setState(state => {
      ...
      return { productList: newProductList };
    });
```
為什麼需要return呢, 不能像這連結裡面給的範例嗎? https://medium.com/@baphemot/understanding-reactjs-setstate-a4640451865b

```
this.setState((state) => ({ value: state.value + 1}));
```
不過我猜想是因為裡面要包一個判斷的function (if/else) 所以要用一個 {}包起來並且給個return
謝謝~

**Comment by Annilla** [comment]
@maggiew61 

> 不過我猜想是因為裡面要包一個判斷的function (if/else) 所以要用一個 {}包起來並且給個return

沒錯喔，詳細 es6 function 怎麼轉成 es5 已經說明在另個 [issue](https://github.com/Annilla/react-shopping-cart/issues/3#issuecomment-522190358) 中，你可以依此類推 ^_−☆
