### ISSUE TITLE
not sure about how reselector works here

### ISSUE THREAD

**Issue by maggiew61** [Annilla/react-shopping-cart#3]
我想請問reselector在<App.js>的邏輯與用法, 以下是我認為應該是這樣的, 想跟你確認, 謝謝

1. 首先我覺得, reselector蠻像是vuex的getter也是針對state的data去重新計算, 不過reselector不會出現在store裡面, 只會透過mapStateToProps在component裡面的state 變成props之後去計算

2.  
把從mapStateToProps 拿到的props傳進去this.props
```   
<div>Cart Total QTY: {subtotalSelector(this.props)}</div>
```

3. 下面的cartItemsSelector 是把傳進來的props的cart提出來
```
const subtotalSelector = createSelector(
  cartItemsSelector,  
  items => items.reduce((acc, item) => acc + item.qty, 0)
);
```

4. 以下這一步驟是我最不確定的地方, 我讀了reselect官網https://github.com/reduxjs/reselect#createselectorinputselectors--inputselectors-resultfunc, 

> Takes one or more selectors, or an array of selectors, computes their values and passes them as arguments to resultFunc.

還有你的文章之後http://annilla.github.io/2019/07/03/JS/React-Redux-Practice/ 認為:
應該是 cartItemSelector會被傳到items.reduce((acc, item) => acc + item.qty, 0) 這個function裡面被重新計算之後return一個值回去給html裡面的Cart Total QTY: {subtotalSelector(this.props)}
```
const subtotalSelector = createSelector(
  cartItemsSelector,  
  items => items.reduce((acc, item) => acc + item.qty, 0)
);
```

謝謝~

**Comment by Annilla** [comment]
@maggiew61
我會把 Selector 想成是專門把丟進去的參數，對每個參數做處理完所產生的新結果 return 出來。

```
const mySelector = createSelector(
  參數1,
  參數2,
  ...
  (參數1, 參數2, ...) => N 個參數的計算公式
)
```

我們可以把 createSelector 想成是一個普通的 function，mySelector 是準備儲存計算結果的變數。
括弧裡面就純粹是 function 待會要執行的相關參數，只是他可以放多個參數，但最後一個要放這些參數的計算公式。然後參數因為不限定屬性(Ex: string, number, object)，所以當你看到參數放object 時就會比較容易產生誤會。

現在來說明原來的程式碼。

首先 82 行是純粹的 es6 function，跟 Selector 無關。

https://github.com/Annilla/react-shopping-cart/blob/e73f0de1a40c407a2ee7812029e5111e7b7173cd/src/App.js#L82

如果轉成 es5 就是

```js
const cartItemsSelector = function(state) { return state.cart; }
或
function cartItemsSelector(state) { return state.cart; }
```

cartItemsSelector 純粹是 return state 裡 cart 屬性出來的 function 而已。這時候還沒丟真的東西進去，所以只是一個工具。

接下來看下一行

https://github.com/Annilla/react-shopping-cart/blob/e73f0de1a40c407a2ee7812029e5111e7b7173cd/src/App.js#L83-L86

我們可以簡化看成

```js
const subtotalSelector = createSelector(
  參數cart 物件,
  參數cart 物件=> 對參數 cart 物件的處理公式
);
```

這時候當 subtotalSelector(this.props) 被執行的時候，就會真的丟東西進去 function createSelector 裡面，然後 cartItemsSelector function 會 return 一個 cart 物件，給 createSelector 做最後一個處理公式的步驟。其實 cartItemsSelector 可以簡化寫在 createSelector 裡面，但想說怕你讀不懂才拆開寫。你可以試試把82行刪掉寫在 createSelector 中會更簡潔！

那麼 cart 物件的處理公式又是怎麼一回事呢？你可以去查詢 reduce 用法和剛剛講的怎麼轉成 es5 的方式，依此類推。可以自己當作 Homework 試試。
